<?php

namespace app\modules\api\v1\messages;
class Module extends \yii\base\Module
{
	public $controllerNamespace = 'app\modules\api\v1\messages\controllers';
	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
	}
}
