<?php

namespace app\modules\v2\user\api;

class Module extends \yii\base\Module {
	public $controllerNamespace = 'app\modules\v2\user\api\controllers';

	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
	}
}
